# Generated by Django 5.0.7 on 2024-11-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffee",
            name="image",
            field=models.ImageField(upload_to="coffee_images/"),
        ),
    ]
