# Generated by Django 5.0.7 on 2024-11-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee", "0003_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coffee",
            name="flavor_profile",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="coffee",
            name="origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
